"""empty message

Revision ID: dc00da55fc8f
Revises: 656ee4ef0fb2
Create Date: 2017-10-05 03:05:15.396477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc00da55fc8f'
down_revision = '656ee4ef0fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
